export default class FixedHeader {
    constructor(app: any, opts?: {});
    app: any;
    mainOpts: any;
    el: any;
    opts: any;
    lis: any;
    preventPin: boolean;
    preventUnpin: boolean;
    _firstLoad: boolean;
    _pinned: boolean;
    _top: boolean;
    _bottom: boolean;
    _small: boolean;
    _altBg: boolean;
    _isResizing: boolean;
    _hiding: boolean;
    lastKnownScrollY: number;
    lastKnownScrollHeight: number;
    currentScrollHeight: number;
    currentScrollY: number;
    mobileMenuOpen: boolean;
    timer: any;
    resetResizeTimer: any;
    intersectingElements: any[];
    initialize(): void;
    pageIsScrolledOnReady: boolean;
    preflight(): void;
    lock(): void;
    unlock(): void;
    isScrolled(): boolean;
    unpinIfScrolled(): void;
    enter(): void;
    setResizeTimer(): void;
    update(): void;
    checkSize(force: any): void;
    checkBg(force: any): void;
    checkTop(force: any): void;
    checkBot(force: any): void;
    checkPin(force: any, toleranceExceeded: any): void;
    redraw(): void;
    notTop(): void;
    top(): void;
    notBottom(): void;
    bottom(): void;
    unpin(): void;
    pin(): void;
    notSmall(): void;
    small(): void;
    notAltBg(): void;
    altBg(): void;
    shouldUnpin(toleranceExceeded: any): any;
    shouldPin(toleranceExceeded: any): any;
    isOutOfBounds(): boolean;
    getScrollerPhysicalHeight(): number;
    getScrollerHeight(): number;
    getDocumentHeight(): number;
    getViewportHeight(): number;
    getElementHeight(el: any): number;
    getElementPhysicalHeight(el: any): number;
    getScrollY(): any;
    toleranceExceeded(): boolean;
    _getOptionsForSection(section: any, opts: any): any;
    _bindMobileMenuListeners(): void;
    _onMobileMenuOpen(): void;
    _onMobileMenuClose(): void;
}
